package vm

const (
	XXPrime1 uint64 = 11400714785074694791
	XXPrime2 uint64 = 14029467366897019727
	XXPrime5 uint64 = 2870177450012600261
)

const (
	TypeName          = "Type"
	ObjectName        = "Object"
	FunctionName      = "Function"
	StringName        = "String"
	BoolName          = "Bool"
	TrueName          = "True"
	FalseName         = "False"
	TupleName         = "Tuple"
	IntegerName       = "Integer"
	FloatName         = "Float"
	ArrayName         = "Array"
	NoneName          = "NoneType"
	BytesName         = "Bytes"
	HashName          = "Hash"
	IteratorName      = "Iterator"
	ModuleName        = "Module"
	None              = "None"
	Source            = "0xFFFFFF"
	TemporalVariable1 = "0xAAAAAA"
	TemporalVariable2 = "0xBBBBBB"
	JunkVariable      = "0N-JUNK-VARIABLE"
)

const (
	Self                    = "self"
	Initialize              = "Initialize"
	NegBits                 = "NegBits"
	Negate                  = "Negate"
	Negative                = "Negative"
	Add                     = "Add"
	RightAdd                = "RightAdd"
	Sub                     = "Sub"
	RightSub                = "RightSub"
	Mul                     = "Mul"
	RightMul                = "RightMul"
	Div                     = "Div"
	RightDiv                = "RightDiv"
	FloorDiv                = "FloorDiv"
	RightFloorDiv           = "RightFloorDiv"
	Mod                     = "Mod"
	RightMod                = "RightMod"
	Pow                     = "Pow"
	RightPow                = "RightPow"
	BitXor                  = "BitXor"
	RightBitXor             = "RightBitXor"
	BitAnd                  = "BitAnd"
	RightBitAnd             = "RightBitAnd"
	BitOr                   = "BitOr"
	RightBitOr              = "RightBitOr"
	BitLeft                 = "BitLeft"
	RightBitLeft            = "RightBitLeft"
	BitRight                = "BitRight"
	RightBitRight           = "RightBitRight"
	And                     = "And"
	RightAnd                = "RightAnd"
	Or                      = "Or"
	RightOr                 = "RightOr"
	Xor                     = "Xor"
	RightXor                = "RightXor"
	Equals                  = "Equals"
	RightEquals             = "RightEquals"
	NotEquals               = "NotEquals"
	RightNotEquals          = "RightNotEquals"
	GreaterThan             = "GreaterThan"
	RightGreaterThan        = "RightGreaterThan"
	LessThan                = "LessThan"
	RightLessThan           = "RightLessThan"
	GreaterThanOrEqual      = "GreaterThanOrEqual"
	RightGreaterThanOrEqual = "RightGreaterThanOrEqual"
	LessThanOrEqual         = "LessThanOrEqual"
	RightLessThanOrEqual    = "RightLessThanOrEqual"
	Hash                    = "Hash"
	Copy                    = "Copy"
	Index                   = "Index"
	Assign                  = "Assign"
	Call                    = "Call"
	Iter                    = "Iter"
	HasNext                 = "HasNext"
	Next                    = "Next"
	Class                   = "Class"
	SubClasses              = "SubClasses"
	ToInteger               = "ToInteger"
	ToFloat                 = "ToFloat"
	ToString                = "ToString"
	ToBool                  = "ToBool"
	ToArray                 = "ToArray"
	ToTuple                 = "ToTuple"
	GetInteger64            = "GetInteger64"
	GetBool                 = "GetBool"
	GetBytes                = "GetBytes"
	GetString               = "GetString"
	GetFloat64              = "GetFloat64"
	GetContent              = "GetContent"
	GetKeyValues            = "GetKeyValues"
	GetLength               = "GetLength"
	SetBool                 = "SetBool"
	SetBytes                = "SetBytes"
	SetString               = "SetString"
	SetInteger64            = "SetInteger64"
	SetFloat64              = "SetFloat64"
	SetContent              = "SetContent"
	SetKeyValues            = "SetKeyValues"
	SetLength               = "SetLength"
	Contains                = "Contains"
)

type ExceptInformation struct {
	Receiver      string
	TargetsLength int
	BodyLength    int
}
