package parser

const (
	ForStatement                = "For Statement"
	UntilStatement              = "Until Statement"
	ModuleStatement             = "Module Statement"
	FunctionDefinitionStatement = "Function Definition Statement"
	ClassStatement              = "Class Statement"
	RaiseStatement              = "Raise Statement"
	TryStatement                = "Try Statement"
	ExceptBlock                 = "Except Block"
	ElseBlock                   = "Else Block"
	FinallyBlock                = "Finally Block"
	BeginStatement              = "Begin Statement"
	EndStatement                = "End Statement"
	InterfaceStatement          = "Interface Statement"
	BinaryExpression            = "Binary Expression"
	PointerExpression           = "Pointer Expression"
	LambdaExpression            = "Lambda Expression"
	ParenthesesExpression       = "Parentheses Expression"
	TupleExpression             = "Tuple Expression"
	ArrayExpression             = "Array Expression"
	HashExpression              = "Hash Expression"
	WhileStatement              = "While Statement"
	DoWhileStatement            = "Do-While Statement"
	IfStatement                 = "If Statement"
	ElifBlock                   = "Elif Block"
	UnlessStatement             = "Unless Statement"
	SwitchStatement             = "Switch Statement"
	CaseBlock                   = "Targets Block"
	DefaultBlock                = "Default Block"
	ReturnStatement             = "Return Statement"
	YieldStatement              = "Yield Statement"
	SuperStatement              = "Super Statement"
	SelectorExpression          = "Selector Expression"
	MethodInvocationExpression  = "Method Invocation Expression"
	IndexExpression             = "Index Expression"
	IfOneLinerExpression        = "If One Liner Expression"
	UnlessOneLinerExpression    = "Unless One Liner Expression"
	OneLineElseBlock            = "One Line Else Block"
	GeneratorExpression         = "Generator Expression"
	AssignStatement             = "Assign Statement"
)
