package common

const (
	HasNextString      = "__has_next__"
	NextString         = "__next__"
	Not                = "__not__"
	Positive           = "__positive__"
	Negative           = "__negative__"
	NegateBits         = "__negate_its__"
	And                = "__and__"
	Or                 = "__or__"
	Xor                = "__xor__"
	In                 = "__in__"
	Is                 = "__is__"
	Implements         = "__implements__"
	Equals             = "__equals__"
	NotEqual           = "__not_equal__"
	GreaterThan        = "__greater_than__"
	GreaterOrEqualThan = "__greater_or_equal_than__"
	LessThan           = "__less_than__"
	LessOrEqualThan    = "__less_or_equal_than__"
	BitwiseOr          = "__bitwise_or__"
	BitwiseXor         = "__bitwise_xor__"
	BitwiseAnd         = "__bitwise_and__"
	BitwiseLeft        = "__bitwise_left__"
	BitwiseRight       = "__bitwise_right__"
	Add                = "__add__"
	Sub                = "__sub__"
	Mul                = "__mul__"
	Div                = "__div__"
	FloorDiv           = "__floor_div__"
	Modulus            = "__mod__"
	PowerOf            = "__pow__"
)
